//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascadeCruises
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cruise
    {
        public int ID { get; set; }
        public int Duration_ID { get; set; }
        public int Ship_ID { get; set; }
        public int Start_Destination_ID { get; set; }
        public int End_Destination_ID { get; set; }
        public System.DateTime Departure_Date { get; set; }
    
        public virtual Cruise_Duration Cruise_Duration { get; set; }
        public virtual Destination Destination { get; set; }
        public virtual Destination Destination1 { get; set; }
        public virtual Ship Ship { get; set; }
    }
}
