//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascadeCruises
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cascade_CruisesEntities : DbContext
    {
        public Cascade_CruisesEntities()
            : base("name=Cascade_CruisesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cruise> Cruises { get; set; }
        public virtual DbSet<Cruise_Duration> Cruise_Duration { get; set; }
        public virtual DbSet<Destination> Destinations { get; set; }
        public virtual DbSet<Passenger> Passengers { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Ship> Ships { get; set; }
    }
}
